name: tableturf_mobile
description: Tableturf Battle for Android

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.30
  soundpool: ^2.3.0
  cupertino_icons: ^1.0.2
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  test: ^1.19.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/card_illustrations/
    - assets/images/card_components/
    - assets/images/card_sleeves/
    - assets/music/
    - assets/sfx/
    - assets/cards.json
    - assets/maps.json

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Splatfont2
      fonts:
        - asset: assets/Splatfont/Splatfont2.ttf
    - family: Splatfont1
      fonts:
        - asset: assets/Splatfont/Splatfont1.otf
    - family: InklingBubble
      fonts:
        - asset: assets/Splatfont/SplatoonBubble.otf

flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icon-adaptive-foreground.png"
  image_path: "assets/icon.png"
  adaptive_icon_background: "#5E47C6"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
